### ISSUE TITLE
**I can not get it to Work !!**

### ISSUE THREAD

**Issue by biniamHaddish** [Mido22/sqlite-to-nedb#1]
**This is how i used it**
 `
var converter = require("sqlite-to-nedb");
var  path = require("path");

var pathofFile  = "./asset/db/EngTig.db";
var destinationFolder ="./asset/db/";

var dbLocation = path.normalize(pathofFile);
var nedbFolder = path.normalize(destinationFolder); 

var ext = '.ne': 

 
// three ways to use the module: 
converter(dbLocation, nedbFolder, ext)  
converter(dbLocation, nedbFolder)    
converter(dbLocation)
console.log(dbLocation);

`
**It throws this below Error at me!!**
/home/biniam/TigDicty/app/app.js:10
var ext = '.ne': 
               ^
SyntaxError: Unexpected token :
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
biniam@debian:~/TigDicty/app$

**Comment by Mido22** [comment]
not sure what the issue can be, what version of node are you using, are you still facing the issue?

**Comment by biniamHaddish** [comment]
Thanks for your reply .I'm using node 0.10 and still the problem exists .

**Comment by Mido22** [comment]
I guess the node version is the issue here, I use arrow functions, promises and keywords like const n let, sorry, but guess you have to update the node to at least v4.0
